### ISSUE TITLE
Issue with constraints in the orders page.

### ISSUE THREAD

**Issue by RishabhRaghunath** [chermo095/test#1]
There was an issue with the way you had setup constraints for the `UIStackView` that you had embedded in a scrollView within the projects in the order page. I've attempted a fix and it now works fine. You can have a look at the file below.
**Project**: [test-master-fixed.zip](https://github.com/chermo095/test/files/4892989/test-master-fixed.zip)
Happy Coding!

**Comment by chermo095** [comment]
Thanks a lot. But wenn I running app , it’s crashing wenn I click on item to open detailsview. I leaved a pic in stackoveflow. Perhaps it’s something wrong with image

**Comment by chermo095** [comment]
![Снимок экрана 2020-07-09 в 10 45 48](https://user-images.githubusercontent.com/65908194/87013270-0c7cff00-c1d3-11ea-83bf-c53354144214.png)

**Comment by chermo095** [comment]
Sorry for interrupting. Maybe I made accidentally a breakpoint. I deleted that and its work fine. Thanks a lot dude.I owe you.

**Comment by RishabhRaghunath** [comment]
Anytime. Glad its solved!
Do upvote and mark as accepted on StackOverflow if it helped you out so it can be closed :)
